// Public import path for all backend code — re-exports from firebase/index.ts.
export {
  app,
  auth,
  db,
  storage,
  getFirebaseAnalytics,
  firebaseConfig,
  getAuthErrorMessage,
  ALLOWED_EMAIL_DOMAIN,
  UMICH_ONLY_ERROR,
  isUmichEmail,
  signInWithGoogle,
  signOutUser,
  reauthenticateWithGoogle,
  deactivateAccount,
  deleteOwnAccount,
  reactivateAccount,
  getUserProfile,
  saveOnboardingProfile,
  saveSignupProfile,
  updateAccountProfile,
  updateUserSettings,
  uploadProfilePhoto,
  DEFAULT_USER_PREFERENCES,
  resolveUserPreferences,
  type AccountProfileUpdate,
  type MessagePolicy,
  type OnboardingPayload,
  type SignupNames,
  type UserPreferences,
  type UserProfile,
  type UserSettingsUpdate,
} from "./firebase";
