export {
  app,
  auth,
  db,
  storage,
  getFirebaseAnalytics,
  firebaseConfig,
  ALLOWED_EMAIL_DOMAIN,
  UMICH_ONLY_ERROR,
  isUmichEmail,
  signUpWithEmail,
  signInWithEmail,
  signInWithGoogle,
  signOutUser,
} from "./firebase";
